version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-barber-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste_db
    ports:
      - "5433:5432"  
    volumes:
      - ../data:/var/lib/postgresql/data

volumes:
  postgres-data: